# Generated by Django 4.2.5 on 2024-05-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_actividad_destino_reserva_delete_ejemplo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actividad',
            new_name='Actividade',
        ),
    ]
